"""Request models of ``/v1/chat`` (also the base of every RAG-backed request)."""

from __future__ import annotations

from typing import Any, Literal

from pydantic import BaseModel, Field, SecretStr, field_validator

from app.core.config import settings
from app.schemas.common import validate_uuid_string


class RagChatMessage(BaseModel):
    role: Literal["user", "assistant", "model"]
    content: str


class RagSourceDocument(BaseModel):
    document_id: str
    kb_id: str
    name: str
    type: str
    status: str

    @field_validator("document_id", "kb_id")
    @classmethod
    def validate_document_uuid(cls, value: str, info: Any) -> str:
        return validate_uuid_string(value, info.field_name) or ""


class RagChatRequest(BaseModel):
    tenant_id: str
    kb_id: str | None = None
    conversation_id: str
    target: Literal["admin", "learner", "lesson_author"]
    model: str
    # The backend's tenant reservation controls capacity. Lesson-author
    # proposals need the same provider window as Blueprints to avoid cutting
    # off source-complete staged unit content.
    max_output_tokens: int = Field(default=2048, ge=1, le=65_536)
    embedding_model: str
    embedding_dimensions: int = 768
    system_prompt: str
    user_message: str
    history: list[RagChatMessage] = Field(default_factory=list)
    source_documents: list[RagSourceDocument] = Field(default_factory=list)
    course_context: str | None = None
    locale: Literal["vi", "en"] = "vi"
    # Correlation is generated by Node once per Course Blueprint execution.
    # It is operational metadata only; it never influences generation.
    correlation_id: str | None = None
    api_key: SecretStr = Field(repr=False)

    @field_validator("tenant_id", "conversation_id")
    @classmethod
    def validate_required_uuid(cls, value: str, info: Any) -> str:
        return validate_uuid_string(value, info.field_name) or ""

    @field_validator("kb_id")
    @classmethod
    def validate_optional_kb_uuid(cls, value: str | None) -> str | None:
        return validate_uuid_string(value, "kb_id")

    @field_validator("correlation_id")
    @classmethod
    def validate_optional_correlation_uuid(cls, value: str | None) -> str | None:
        return validate_uuid_string(value, "correlation_id")

    @field_validator("user_message")
    @classmethod
    def validate_user_message(cls, value: str) -> str:
        text = value.strip()
        if not text:
            raise ValueError("Tin nhắn không được để trống.")
        if len(text) > settings.max_user_message_chars:
            raise ValueError(f"Tin nhắn vượt quá {settings.max_user_message_chars} ký tự.")
        return text

    @field_validator("source_documents")
    @classmethod
    def validate_source_document_count(cls, value: list[RagSourceDocument]) -> list[RagSourceDocument]:
        if len(value) > 20:
            raise ValueError("Tối đa 20 tài liệu nguồn cho mỗi request RAG.")
        return value
